// Generated by scripts/build-theme-plugins.mjs; edit themes.json or scripts/theme-kit/runtime.js.
async function activateTheme(ctx, config) {
  const { defineComponent, h, ref, watch, onMounted, onBeforeUnmount } =
    ctx.vue;
  const files = config.files;
  const urls = Object.fromEntries(
    await Promise.all(
      files.map(async (file) => {
        const result = await ctx.fs.getFileUrl(
          `${ctx.descriptor.directory}/assets/${config.id}/${file}`,
        );
        if (!result.ok || !result.url)
          throw new Error(`无法载入主题资源：${file}`);
        return [file, result.url];
      }),
    ),
  );
  const fill = {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    pointerEvents: "none",
  };
  const image = (file, radius) =>
    h("img", {
      src: urls[file],
      alt: "",
      draggable: false,
      style: { ...fill, filter: radius ? `blur(${radius}px)` : undefined },
    });
  const Autumn = defineComponent({
    name: "QQLocalAutumn",
    setup() {
      const root = ref(null),
        theme = ctx.theme.useTheme();
      let animations = [],
        observer;
      const sync = () =>
        animations.forEach((animation) =>
          theme.motionEnabled.value ? animation.play() : animation.pause(),
        );
      const rebuild = () => {
        animations.forEach((animation) => animation.cancel());
        const height = root.value.clientHeight,
          width = root.value.clientWidth;
        animations = [...root.value.querySelectorAll("[data-leaf]")].map(
          (leaf, i) => {
            const start = width * ((i * 0.137 + 0.08) % 1);
            const animation = leaf.animate(
              [
                {
                  transform: `translate(${start}px,-90px) rotate(0deg)`,
                  opacity: 0,
                },
                { offset: 0.12, opacity: 0.9 },
                { offset: 0.825, opacity: 0.9 },
                {
                  offset: 15 / 16,
                  transform: `translate(${start - width * 0.25}px,${height + 90}px) rotate(${i % 2 ? 360 : -280}deg)`,
                  opacity: 0,
                },
              ],
              { duration: 16000, iterations: Infinity, easing: "linear" },
            );
            animation.currentTime = i * 2000;
            return animation;
          },
        );
        sync();
      };
      onMounted(() => {
        observer = new ResizeObserver(rebuild);
        observer.observe(root.value);
      });
      watch(theme.motionEnabled, sync);
      onBeforeUnmount(() => {
        observer?.disconnect();
        animations.forEach((animation) => animation.cancel());
        animations = [];
      });
      return () =>
        h(
          "div",
          {
            ref: root,
            "aria-hidden": "true",
            style: { ...fill, overflow: "hidden" },
          },
          [
            image("autumn.png", theme.imageBlur.value),
            ...Array.from({ length: 8 }, (_, i) =>
              h("img", {
                "data-leaf": "",
                src: urls["leaf.png"],
                alt: "",
                draggable: false,
                style: {
                  position: "absolute",
                  top: 0,
                  left: 0,
                  width: `${43 * (1.2 + (0.8 * i) / 7)}px`,
                  height: "auto",
                  opacity: 0,
                },
              }),
            ),
          ],
        );
    },
  });
  const videoBackground = (name) =>
    defineComponent({
      name: `QQLocalVideo-${name}`,
      setup() {
        const video = ref(null),
          ready = ref(false),
          failed = ref(false),
          theme = ctx.theme.useTheme();
        let disposed = false;
        let pending = false;
        let retryTimer = null;
        let failures = 0;
        const clearRetry = () => {
          if (retryTimer !== null) clearTimeout(retryTimer);
          retryTimer = null;
        };
        const retry = () => {
          if (
            disposed ||
            !theme.motionEnabled.value ||
            retryTimer !== null ||
            failures >= 3
          )
            return;
          failures++;
          retryTimer = setTimeout(() => {
            retryTimer = null;
            const element = video.value;
            if (!element || disposed || !theme.motionEnabled.value) return;
            if (element.error) element.load();
            sync();
          }, 300 * failures);
        };
        const sync = () => {
          const element = video.value;
          if (!element || disposed) return;
          if (!theme.motionEnabled.value) {
            clearRetry();
            element.pause();
            return;
          }
          if (pending || (!element.paused && !element.error)) return;
          // Assign media properties before play, including after a hidden-window pause.
          element.muted = element.defaultMuted = true;
          // All video themes use the source playback speed.
          element.defaultPlaybackRate = element.playbackRate = 1;
          pending = true;
          element
            .play()
            .then(() => {
              if (disposed) return;
              if (!theme.motionEnabled.value) {
                element.pause();
                return;
              }
              failures = 0;
              failed.value = false;
              ready.value = true;
              clearRetry();
            })
            .catch((error) => {
              if (disposed || !theme.motionEnabled.value) return;
              if (error.name !== "AbortError") {
                failed.value = true;
                ready.value = false;
                console.warn(`[theme] ${name} playback failed`, error.name);
              }
              retry();
            })
            .finally(() => {
              pending = false;
            });
        };
        onMounted(sync);
        watch(theme.motionEnabled, () => {
          failures = 0;
          sync();
        });
        onBeforeUnmount(() => {
          disposed = true;
          clearRetry();
          if (video.value) {
            video.value.pause();
            video.value.removeAttribute("src");
            video.value.load();
          }
        });
        return () =>
          h("div", { "aria-hidden": "true", style: fill }, [
            image(config.poster, theme.imageBlur.value),
            h("video", {
              ref: video,
              src: urls[config.video],
              muted: true,
              loop: true,
              playsinline: true,
              preload: "auto",
              onLoadeddata: () => {
                ready.value = true;
                sync();
              },
              onCanplay: sync,
              onPlaying: () => {
                failures = 0;
                failed.value = false;
                ready.value = true;
                clearRetry();
              },
              onPause: retry,
              onError: () => {
                failed.value = true;
                ready.value = false;
                retry();
              },
              style: { ...fill, opacity: ready.value && !failed.value ? 1 : 0 },
            }),
          ]);
      },
    });
  const SpriteScene = defineComponent({
    name: `ThemeScene-${config.id}`,
    setup() {
      const root = ref(null),
        canvas = ref(null),
        theme = ctx.theme.useTheme();
      let observer,
        animations = [];
      const sync = () =>
        animations.forEach((a) =>
          theme.motionEnabled.value ? a.play() : a.pause(),
        );
      onMounted(() => {
        const resize = () => {
          const scale = Math.max(
            root.value.clientWidth / 1380,
            root.value.clientHeight / 780,
          );
          canvas.value.style.transform = `translate(-50%, -50%) scale(${scale})`;
        };
        observer = new ResizeObserver(resize);
        observer.observe(root.value);
        resize();
        const elements = [...canvas.value.querySelectorAll("[data-sprite]")];
        animations = config.layers.flatMap((layer, i) => {
          if (!layer.frames) return [];
          const animation = elements[i].animate(layer.frames, {
            duration: layer.duration,
            iterations: Infinity,
            easing: layer.easing || "ease-in-out",
            direction: layer.direction || "alternate",
          });
          animation.currentTime = layer.offset || 0;
          return [animation];
        });
        sync();
      });
      watch(theme.motionEnabled, sync);
      onBeforeUnmount(() => {
        observer?.disconnect();
        animations.forEach((a) => a.cancel());
        animations = [];
      });
      return () =>
        h(
          "div",
          {
            ref: root,
            "aria-hidden": "true",
            style: { ...fill, overflow: "hidden" },
          },
          [
            h(
              "div",
              {
                ref: canvas,
                style: {
                  position: "absolute",
                  width: "1380px",
                  height: "780px",
                  left: "50%",
                  top: "50%",
                  transformOrigin: "center",
                  transform: "translate(-50%, -50%)",
                },
              },
              [
                image(config.background, theme.imageBlur.value),
                ...config.layers.map((layer, i) =>
                  h(
                    "div",
                    {
                      key: i,
                      "data-sprite": "",
                      style: {
                        position: "absolute",
                        left: `${layer.x}px`,
                        top: `${layer.y}px`,
                        width: `${layer.crop[2]}px`,
                        height: `${layer.crop[3]}px`,
                        transformOrigin: layer.origin || "center",
                        overflow: "hidden",
                      },
                    },
                    [
                      h("img", {
                        src: urls[config.sprite],
                        alt: "",
                        draggable: false,
                        style: {
                          position: "absolute",
                          maxWidth: "none",
                          width: `${config.spriteSize[0]}px`,
                          height: `${config.spriteSize[1]}px`,
                          left: `${-layer.crop[0]}px`,
                          top: `${-layer.crop[1]}px`,
                        },
                      }),
                    ],
                  ),
                ),
              ],
            ),
          ],
        );
    },
  });
  const dark = config.dark;
  const variant = {
    accent: config.accent,
    tokens: {
      shell: config.shell,
      main: config.shell,
      text: dark ? "#f6f3ef" : "#28231e",
      secondary: dark ? "#c9c2ba" : "#615a52",
      ...config.tokens,
    },
    background: {
      color: config.shell,
      ...(config.kind === "static"
        ? { image: urls[config.background], fit: "cover", position: "center" }
        : {}),
    },
  };
  const decoration =
    config.kind === "video"
      ? videoBackground(config.id)
      : config.kind === "autumn"
        ? Autumn
        : config.kind === "sprites"
          ? SpriteScene
          : null;
  ctx.theme.register({
    id: config.id,
    title: config.title,
    type: config.kind === "static" ? "default" : "dynamic",
    defaultMode: dark ? "dark" : "light",
    preview: urls[config.poster],
    description: config.description,
    variants: { light: variant, dark: variant },
    ...(decoration ? { decorations: { background: decoration } } : {}),
  });
}

export async function activate(ctx) {
  const themes = [
  {
    "id": "autumn",
    "title": "秋日枫叶",
    "kind": "autumn",
    "description": "暖橙色秋景，枫叶缓缓飘落。",
    "dark": true,
    "shell": "#d07a00",
    "accent": "#F1CF0B",
    "files": [
      "autumn.png",
      "leaf.png"
    ],
    "poster": "autumn.png",
    "tokens": {
      "card": "#36363a",
      "elevated": "#36363a",
      "border": "#55555a"
    }
  },
  {
    "id": "prism",
    "title": "幻彩",
    "kind": "video",
    "description": "流动的柔和彩光，交织成连续变化的背景。",
    "dark": true,
    "shell": "#29292b",
    "accent": "#11BE71",
    "files": [
      "prism.png",
      "prism-flow.mp4"
    ],
    "poster": "prism.png",
    "video": "prism-flow.mp4",
    "tokens": {
      "card": "#36363a",
      "elevated": "#36363a",
      "border": "#55555a"
    }
  },
  {
    "id": "golden-ribbon",
    "title": "金丝带",
    "kind": "video",
    "description": "深色背景上的金色丝带，舒缓流转。",
    "dark": true,
    "shell": "#010101",
    "accent": "#CD8038",
    "files": [
      "golden-ribbon.png",
      "golden-ribbon.mp4"
    ],
    "poster": "golden-ribbon.png",
    "video": "golden-ribbon.mp4",
    "tokens": {
      "card": "#36363a",
      "elevated": "#36363a",
      "border": "#55555a"
    }
  },
  {
    "id": "willow",
    "title": "杨柳依依",
    "kind": "sprites",
    "description": "晴空与草地间，柳枝轻摆，列车驶过远方。",
    "dark": false,
    "shell": "#318BA4",
    "accent": "#FFDE00",
    "files": [
      "background.png",
      "sprites.png",
      "preview.png"
    ],
    "background": "background.png",
    "sprite": "sprites.png",
    "spriteSize": [
      1384,
      870
    ],
    "poster": "preview.png",
    "layers": [
      {
        "crop": [
          726,
          348,
          466,
          45
        ],
        "x": -466,
        "y": 620,
        "easing": "linear",
        "direction": "normal",
        "frames": [
          {
            "transform": "translate(0px,0px)"
          },
          {
            "transform": "translate(1846px,0px)"
          }
        ],
        "duration": 24000
      },
      {
        "crop": [
          2,
          141,
          344,
          727
        ],
        "x": 0,
        "y": 48
      },
      {
        "crop": [
          348,
          629,
          276,
          227
        ],
        "x": 2,
        "y": 177,
        "origin": "16.0px 15.0px",
        "frames": [
          {
            "transform": "rotate(-3deg)"
          },
          {
            "transform": "rotate(3deg)"
          }
        ],
        "duration": 3500
      },
      {
        "crop": [
          861,
          620,
          227,
          215
        ],
        "x": 232,
        "y": 133,
        "origin": "5.0px 12.0px",
        "frames": [
          {
            "transform": "rotate(-2deg)"
          },
          {
            "transform": "rotate(2deg)"
          }
        ],
        "duration": 7000
      },
      {
        "crop": [
          726,
          141,
          222,
          205
        ],
        "x": 35,
        "y": 132,
        "origin": "1.0px 18.0px",
        "frames": [
          {
            "transform": "rotate(-2deg)"
          },
          {
            "transform": "rotate(2deg)"
          }
        ],
        "duration": 4500
      },
      {
        "crop": [
          716,
          399,
          199,
          219
        ],
        "x": 175,
        "y": 138,
        "origin": "14.0px 12.0px",
        "frames": [
          {
            "transform": "rotate(-3.5deg)"
          },
          {
            "transform": "rotate(3.5deg)"
          }
        ],
        "duration": 5000
      },
      {
        "crop": [
          917,
          395,
          212,
          197
        ],
        "x": 317,
        "y": 135,
        "origin": "5.0px 3.0px",
        "frames": [
          {
            "transform": "rotate(-3deg)"
          },
          {
            "transform": "rotate(3deg)"
          }
        ],
        "duration": 4000
      },
      {
        "crop": [
          443,
          141,
          281,
          256
        ],
        "x": 177,
        "y": 142,
        "origin": "17.0px 8.0px",
        "frames": [
          {
            "transform": "rotate(-2.5deg)"
          },
          {
            "transform": "rotate(2.5deg)"
          }
        ],
        "duration": 3500
      },
      {
        "crop": [
          1131,
          395,
          196,
          183
        ],
        "x": 5,
        "y": 171,
        "origin": "19.0px 6.0px",
        "frames": [
          {
            "transform": "rotate(-2deg)"
          },
          {
            "transform": "rotate(2deg)"
          }
        ],
        "duration": 5500
      },
      {
        "crop": [
          950,
          141,
          163,
          200
        ],
        "x": 88,
        "y": 103,
        "origin": "22.0px 15.0px",
        "frames": [
          {
            "transform": "rotate(-3.5deg)"
          },
          {
            "transform": "rotate(3.5deg)"
          }
        ],
        "duration": 4000
      },
      {
        "crop": [
          626,
          623,
          233,
          240
        ],
        "x": 18,
        "y": 87,
        "origin": "9.0px 12.0px",
        "frames": [
          {
            "transform": "rotate(-2deg)"
          },
          {
            "transform": "rotate(2deg)"
          }
        ],
        "duration": 3500
      },
      {
        "crop": [
          1194,
          141,
          184,
          191
        ],
        "x": 140,
        "y": 79,
        "origin": "57.0px 55.0px",
        "frames": [
          {
            "transform": "rotate(-3deg)"
          },
          {
            "transform": "rotate(3deg)"
          }
        ],
        "duration": 5000
      },
      {
        "crop": [
          1131,
          580,
          122,
          130
        ],
        "x": 178,
        "y": 52,
        "origin": "28.0px 7.0px",
        "frames": [
          {
            "transform": "rotate(-3deg)"
          },
          {
            "transform": "rotate(3deg)"
          }
        ],
        "duration": 3500
      },
      {
        "crop": [
          443,
          399,
          271,
          222
        ],
        "x": 271,
        "y": 130,
        "origin": "12.0px 11.0px",
        "frames": [
          {
            "transform": "rotate(-2deg)"
          },
          {
            "transform": "rotate(2deg)"
          }
        ],
        "duration": 4000
      },
      {
        "crop": [
          348,
          141,
          93,
          486
        ],
        "x": 62,
        "y": 166,
        "origin": "10px 0px",
        "frames": [
          {
            "transform": "rotate(-5deg)"
          },
          {
            "transform": "rotate(5deg)"
          }
        ],
        "duration": 6000
      },
      {
        "crop": [
          1255,
          580,
          91,
          118
        ],
        "x": 65,
        "y": 547,
        "origin": "7px -381px",
        "frames": [
          {
            "transform": "rotate(-5deg)"
          },
          {
            "transform": "rotate(5deg)"
          }
        ],
        "duration": 6000
      },
      {
        "crop": [
          2,
          2,
          1380,
          137
        ],
        "x": 0,
        "y": 643,
        "origin": "50% 100%",
        "frames": [
          {
            "transform": "skewX(-1deg)"
          },
          {
            "transform": "skewX(1deg)"
          }
        ],
        "duration": 6000
      }
    ]
  },
  {
    "id": "ferris-wheel",
    "title": "旋转摩天轮",
    "kind": "sprites",
    "description": "粉色游乐园里，摩天轮缓缓转动，气球随风轻浮。",
    "dark": false,
    "shell": "#f2c0c3",
    "accent": "#a52656",
    "files": [
      "background.png",
      "sprites.png",
      "preview.png"
    ],
    "background": "background.png",
    "sprite": "sprites.png",
    "spriteSize": [
      1384,
      566
    ],
    "poster": "preview.png",
    "layers": [
      {
        "crop": [
          1144,
          256,
          108,
          145
        ],
        "x": 342,
        "y": 539
      },
      {
        "crop": [
          713,
          153,
          277,
          309
        ],
        "x": 95,
        "y": 375
      },
      {
        "crop": [
          302,
          153,
          409,
          410
        ],
        "x": 16,
        "y": 177,
        "easing": "linear",
        "direction": "normal",
        "frames": [
          {
            "transform": "rotate(0deg)"
          },
          {
            "transform": "rotate(360deg)"
          }
        ],
        "duration": 30000
      },
      {
        "crop": [
          2,
          153,
          298,
          411
        ],
        "x": 35,
        "y": 278
      },
      {
        "crop": [
          2,
          2,
          1380,
          149
        ],
        "x": 0,
        "y": 631
      },
      {
        "crop": [
          1144,
          153,
          149,
          101
        ],
        "x": 92,
        "y": 679
      },
      {
        "crop": [
          992,
          153,
          150,
          132
        ],
        "x": 92,
        "y": 608,
        "origin": "15% 90%",
        "frames": [
          {
            "transform": "rotate(-3deg)"
          },
          {
            "transform": "rotate(3deg)"
          }
        ],
        "duration": 5000
      },
      {
        "crop": [
          713,
          464,
          103,
          76
        ],
        "x": 74,
        "y": 588
      },
      {
        "crop": [
          859,
          464,
          89,
          54
        ],
        "x": 152,
        "y": 606,
        "origin": "0% 50%",
        "frames": [
          {
            "transform": "rotate(-5deg)"
          },
          {
            "transform": "rotate(5deg)"
          }
        ],
        "duration": 4000
      },
      {
        "crop": [
          818,
          464,
          39,
          69
        ],
        "x": 1246,
        "y": 237,
        "frames": [
          {
            "transform": "translate(0px,0px)"
          },
          {
            "transform": "translate(0px,-16px)"
          }
        ],
        "duration": 6500
      },
      {
        "crop": [
          950,
          464,
          39,
          54
        ],
        "x": 674,
        "y": 84,
        "frames": [
          {
            "transform": "translate(0px,0px)"
          },
          {
            "transform": "translate(0px,20px)"
          }
        ],
        "duration": 7500
      }
    ]
  }
];
  for (const config of themes) await activateTheme(ctx, config);
}
