// Generated by scripts/build-theme-plugins.mjs; edit themes.json or scripts/theme-kit/runtime.js.
async function activateTheme(ctx, config) {
  const { defineComponent, h, ref, watch, onMounted, onBeforeUnmount } =
    ctx.vue;
  const files = config.files;
  const urls = Object.fromEntries(
    await Promise.all(
      files.map(async (file) => {
        const result = await ctx.fs.getFileUrl(
          `${ctx.descriptor.directory}/assets/${config.id}/${file}`,
        );
        if (!result.ok || !result.url)
          throw new Error(`无法载入主题资源：${file}`);
        return [file, result.url];
      }),
    ),
  );
  const fill = {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    pointerEvents: "none",
  };
  const image = (file, radius) =>
    h("img", {
      src: urls[file],
      alt: "",
      draggable: false,
      style: { ...fill, filter: radius ? `blur(${radius}px)` : undefined },
    });
  const Autumn = defineComponent({
    name: "QQLocalAutumn",
    setup() {
      const root = ref(null),
        theme = ctx.theme.useTheme();
      let animations = [],
        observer;
      const sync = () =>
        animations.forEach((animation) =>
          theme.motionEnabled.value ? animation.play() : animation.pause(),
        );
      const rebuild = () => {
        animations.forEach((animation) => animation.cancel());
        const height = root.value.clientHeight,
          width = root.value.clientWidth;
        animations = [...root.value.querySelectorAll("[data-leaf]")].map(
          (leaf, i) => {
            const start = width * ((i * 0.137 + 0.08) % 1);
            const animation = leaf.animate(
              [
                {
                  transform: `translate(${start}px,-90px) rotate(0deg)`,
                  opacity: 0,
                },
                { offset: 0.12, opacity: 0.9 },
                { offset: 0.825, opacity: 0.9 },
                {
                  offset: 15 / 16,
                  transform: `translate(${start - width * 0.25}px,${height + 90}px) rotate(${i % 2 ? 360 : -280}deg)`,
                  opacity: 0,
                },
              ],
              { duration: 16000, iterations: Infinity, easing: "linear" },
            );
            animation.currentTime = i * 2000;
            return animation;
          },
        );
        sync();
      };
      onMounted(() => {
        observer = new ResizeObserver(rebuild);
        observer.observe(root.value);
      });
      watch(theme.motionEnabled, sync);
      onBeforeUnmount(() => {
        observer?.disconnect();
        animations.forEach((animation) => animation.cancel());
        animations = [];
      });
      return () =>
        h(
          "div",
          {
            ref: root,
            "aria-hidden": "true",
            style: { ...fill, overflow: "hidden" },
          },
          [
            image("autumn.png", theme.imageBlur.value),
            ...Array.from({ length: 8 }, (_, i) =>
              h("img", {
                "data-leaf": "",
                src: urls["leaf.png"],
                alt: "",
                draggable: false,
                style: {
                  position: "absolute",
                  top: 0,
                  left: 0,
                  width: `${43 * (1.2 + (0.8 * i) / 7)}px`,
                  height: "auto",
                  opacity: 0,
                },
              }),
            ),
          ],
        );
    },
  });
  const videoBackground = (name) =>
    defineComponent({
      name: `QQLocalVideo-${name}`,
      setup() {
        const video = ref(null),
          ready = ref(false),
          failed = ref(false),
          theme = ctx.theme.useTheme();
        let disposed = false;
        let pending = false;
        let retryTimer = null;
        let failures = 0;
        const clearRetry = () => {
          if (retryTimer !== null) clearTimeout(retryTimer);
          retryTimer = null;
        };
        const retry = () => {
          if (
            disposed ||
            !theme.motionEnabled.value ||
            retryTimer !== null ||
            failures >= 3
          )
            return;
          failures++;
          retryTimer = setTimeout(() => {
            retryTimer = null;
            const element = video.value;
            if (!element || disposed || !theme.motionEnabled.value) return;
            if (element.error) element.load();
            sync();
          }, 300 * failures);
        };
        const sync = () => {
          const element = video.value;
          if (!element || disposed) return;
          if (!theme.motionEnabled.value) {
            clearRetry();
            element.pause();
            return;
          }
          if (pending || (!element.paused && !element.error)) return;
          // Assign media properties before play, including after a hidden-window pause.
          element.muted = element.defaultMuted = true;
          // All video themes use the source playback speed.
          element.defaultPlaybackRate = element.playbackRate = 1;
          pending = true;
          element
            .play()
            .then(() => {
              if (disposed) return;
              if (!theme.motionEnabled.value) {
                element.pause();
                return;
              }
              failures = 0;
              failed.value = false;
              ready.value = true;
              clearRetry();
            })
            .catch((error) => {
              if (disposed || !theme.motionEnabled.value) return;
              if (error.name !== "AbortError") {
                failed.value = true;
                ready.value = false;
                console.warn(`[theme] ${name} playback failed`, error.name);
              }
              retry();
            })
            .finally(() => {
              pending = false;
            });
        };
        onMounted(sync);
        watch(theme.motionEnabled, () => {
          failures = 0;
          sync();
        });
        onBeforeUnmount(() => {
          disposed = true;
          clearRetry();
          if (video.value) {
            video.value.pause();
            video.value.removeAttribute("src");
            video.value.load();
          }
        });
        return () =>
          h("div", { "aria-hidden": "true", style: fill }, [
            image(config.poster, theme.imageBlur.value),
            h("video", {
              ref: video,
              src: urls[config.video],
              muted: true,
              loop: true,
              playsinline: true,
              preload: "auto",
              onLoadeddata: () => {
                ready.value = true;
                sync();
              },
              onCanplay: sync,
              onPlaying: () => {
                failures = 0;
                failed.value = false;
                ready.value = true;
                clearRetry();
              },
              onPause: retry,
              onError: () => {
                failed.value = true;
                ready.value = false;
                retry();
              },
              style: { ...fill, opacity: ready.value && !failed.value ? 1 : 0 },
            }),
          ]);
      },
    });
  const SpriteScene = defineComponent({
    name: `ThemeScene-${config.id}`,
    setup() {
      const root = ref(null),
        canvas = ref(null),
        theme = ctx.theme.useTheme();
      let observer,
        animations = [];
      const sync = () =>
        animations.forEach((a) =>
          theme.motionEnabled.value ? a.play() : a.pause(),
        );
      onMounted(() => {
        const resize = () => {
          const scale = Math.max(
            root.value.clientWidth / 1380,
            root.value.clientHeight / 780,
          );
          canvas.value.style.transform = `translate(-50%, -50%) scale(${scale})`;
        };
        observer = new ResizeObserver(resize);
        observer.observe(root.value);
        resize();
        const elements = [...canvas.value.querySelectorAll("[data-sprite]")];
        animations = config.layers.flatMap((layer, i) => {
          if (!layer.frames) return [];
          const animation = elements[i].animate(layer.frames, {
            duration: layer.duration,
            iterations: Infinity,
            easing: layer.easing || "ease-in-out",
            direction: layer.direction || "alternate",
          });
          animation.currentTime = layer.offset || 0;
          return [animation];
        });
        sync();
      });
      watch(theme.motionEnabled, sync);
      onBeforeUnmount(() => {
        observer?.disconnect();
        animations.forEach((a) => a.cancel());
        animations = [];
      });
      return () =>
        h(
          "div",
          {
            ref: root,
            "aria-hidden": "true",
            style: { ...fill, overflow: "hidden" },
          },
          [
            h(
              "div",
              {
                ref: canvas,
                style: {
                  position: "absolute",
                  width: "1380px",
                  height: "780px",
                  left: "50%",
                  top: "50%",
                  transformOrigin: "center",
                  transform: "translate(-50%, -50%)",
                },
              },
              [
                image(config.background, theme.imageBlur.value),
                ...config.layers.map((layer, i) =>
                  h(
                    "div",
                    {
                      key: i,
                      "data-sprite": "",
                      style: {
                        position: "absolute",
                        left: `${layer.x}px`,
                        top: `${layer.y}px`,
                        width: `${layer.crop[2]}px`,
                        height: `${layer.crop[3]}px`,
                        transformOrigin: layer.origin || "center",
                        overflow: "hidden",
                      },
                    },
                    [
                      h("img", {
                        src: urls[config.sprite],
                        alt: "",
                        draggable: false,
                        style: {
                          position: "absolute",
                          maxWidth: "none",
                          width: `${config.spriteSize[0]}px`,
                          height: `${config.spriteSize[1]}px`,
                          left: `${-layer.crop[0]}px`,
                          top: `${-layer.crop[1]}px`,
                        },
                      }),
                    ],
                  ),
                ),
              ],
            ),
          ],
        );
    },
  });
  const dark = config.dark;
  const variant = {
    accent: config.accent,
    tokens: {
      shell: config.shell,
      main: config.shell,
      text: dark ? "#f6f3ef" : "#28231e",
      secondary: dark ? "#c9c2ba" : "#615a52",
      ...config.tokens,
    },
    background: {
      color: config.shell,
      ...(config.kind === "static"
        ? { image: urls[config.background], fit: "cover", position: "center" }
        : {}),
    },
  };
  const decoration =
    config.kind === "video"
      ? videoBackground(config.id)
      : config.kind === "autumn"
        ? Autumn
        : config.kind === "sprites"
          ? SpriteScene
          : null;
  ctx.theme.register({
    id: config.id,
    title: config.title,
    type: config.kind === "static" ? "default" : "dynamic",
    defaultMode: dark ? "dark" : "light",
    preview: urls[config.poster],
    description: config.description,
    variants: { light: variant, dark: variant },
    ...(decoration ? { decorations: { background: decoration } } : {}),
  });
}

export async function activate(ctx) {
  const themes = [
  {
    "id": "sky-of-love",
    "title": "恋空",
    "kind": "static",
    "description": "清新的青蓝色背景，点缀轻盈的字母纹样。",
    "dark": false,
    "shell": "#80e3e5",
    "accent": "#0165ab",
    "files": [
      "background.png"
    ],
    "background": "background.png",
    "poster": "background.png"
  },
  {
    "id": "honey-pink",
    "title": "哈尼粉",
    "kind": "static",
    "description": "柔和粉色与樱桃图案，带来轻甜的夏日气息。",
    "dark": false,
    "shell": "#eb8fa2",
    "accent": "#e10b65",
    "files": [
      "background.png"
    ],
    "background": "background.png",
    "poster": "background.png"
  }
];
  for (const config of themes) await activateTheme(ctx, config);
}
